### ISSUE TITLE
Question: How to set up the system

### ISSUE THREAD

**Issue by fermuch** [msantos/stdio#1]
Hello! This is a very interesting library, and I wanted to try using it but any call I try to do ends up in the error `shell process exited with reason: {:error, {:error, :eagain}}`

After digging a bit in `prx`'s docs, I've seen the same error starts happening after executing `application:set_env(prx, options, [{exec, "sudo -n"}])`, so maybe it is related to privileges?

Can you provide an example of how to set up the host to run isolated processes? Or maybe a docker image to run the library?

Thanks!

**Comment by msantos** [comment]
@fermuch thanks for trying out the library and for opening an issue!

The `shell process exited with reason: {:error, {:error, :eagain}}` error can happen if the `prx` binary can't be executed. Can you check if `prx` is runnable from the command line?

```
stdio(main)$ ./deps/prx/priv/prx -h
prx 0.40.5
usage: prx -c <path> [<options>]
```

By default, stdio doesn't elevate privileges so the `sudo` configuration should not be a problem.

**Comment by fermuch** [comment]
Ah, that makes sense! Thanks.

Somehow I totally forgot to read the part about [setuid](https://hexdocs.pm/stdio/Stdio.html#setuid/0).

After setting up permissions to `prx` and granting it access to `sudo` as specified in the docs, I can run containers!

```elixir
iex(1)> Stdio.setuid()
:ok
iex(2)> Stdio.Container.make_chroot_tree!()
:ok
iex(3)> Stdio.stream!("ip -br addr show", Stdio.Rootless) |> Enum.to_list()
[stdout: "lo               DOWN           \n", exit_status: 0]
```

But trying to grant it access to the network still gives me the same error:

```elixir
iex(4)> Stdio.stream!("ping -c 1 8.8.8.8", Stdio.Container, setuid: true, net: :host) |> Enum.to_list()
** (Stdio.OpError) error attempting to fork subprocess: insufficient permissions (eperm)

    (stdio 0.4.3) lib/stdio/op.ex:124: Stdio.Op.task!/4
    (stdio 0.4.3) lib/stdio.ex:676: Stdio.__fork__/6
    (stdio 0.4.3) lib/stdio/stream.ex:41: Stdio.Stream.stream_init/7
    (elixir 1.16.3) lib/stream.ex:1612: anonymous fn/5 in Stream.resource/3
    (elixir 1.16.3) lib/enum.ex:4396: Enum.reverse/1
    (elixir 1.16.3) lib/enum.ex:3728: Enum.to_list/1
    iex:4: (file)
```

Did I miss something else in the docs?

**Comment by msantos** [comment]
Test running `prx` from the command line using `sudo`:

```
$ sudo ./deps/prx/priv/prx -h
prx 0.40.5
usage: prx -c <path> [<options>]
```

If `sudo` fails, check the [sudoers](https://hexdocs.pm/stdio/Stdio.html#setuid/0-sudo-8) configuration.

`Stdio.Rootless` works without setuid but `Stdio.Container` does which may explain why `Rootless` worked but ping failed:

```elixir
iex(1)> Stdio.stream!("ip -br addr show", Stdio.Rootless) |> Enum.to_list()
[stdout: "lo               DOWN           \n", exit_status: 0]
iex(2)> Stdio.stream!("ping -c 1 8.8.8.8", Stdio.Container, setuid: true, net: :host) |> Enum.to_list()
** (Stdio.OpError) error attempting to fork subprocess: insufficient permissions (eperm)

    (stdio 0.4.3) lib/stdio/op.ex:124: Stdio.Op.task!/4
    (stdio 0.4.3) lib/stdio.ex:676: Stdio.__fork__/6
    (stdio 0.4.3) lib/stdio/stream.ex:41: Stdio.Stream.stream_init/7
    (elixir 1.17.2) lib/stream.ex:1675: anonymous fn/5 in Stream.resource/3
    (elixir 1.17.2) lib/enum.ex:4423: Enum.reverse/1
    (elixir 1.17.2) lib/enum.ex:3748: Enum.to_list/1
    iex:2: (file)
iex(2)> Stdio.setuid()
:ok
iex(3)> Stdio.stream!("ping -c 1 8.8.8.8", Stdio.Container, setuid: true, net: :host) |> Enum.to_list()
[
  stdout: "PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.\n64 bytes from 8.8.8.8: icmp_seq=1 ttl=117 time=18.8 ms\n\n--- 8.8.8.8 ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 18.794/18.794/18.794/0.000 ms\n",
  exit_status: 0
]
```

**Comment by fermuch** [comment]
Oh, that is working now! Is `setuid` global or do I need to set it before each call to `stream!`?

**Comment by msantos** [comment]
Excellent, glad to hear it is working for you now! Thank you, appreciate your patience working through the install process. I'll look into adding some installation and debugging steps to the README.

`Setuid/0` is global: the function calls `application:set_env(prx, options, [{exec, "sudo -n"}])`
